import { Geist, Geist_Mono } from "next/font/google"; // Import Google fonts
import "./globals.css"; // Import global styles

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.JS To-Do List", // Set the title of the page
  description: "Generated by create next app", // Set the description of the page
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children} {/* Render children components */}
      </body>
    </html>
  );
}
